# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def common_install
  pod 'ReactorKit'
end


target 'Depth' do
  common_install
end

target 'DepthTests' do
  common_install
end
